### ISSUE TITLE
Выпилить неиспользуемые хелперы

### ISSUE THREAD

**Issue by prodderman** [fullstack-development/react-redux-starter-kit#157]
- [x] [Выпилить shared/helpers/decorators](https://github.com/fullstack-development/react-redux-starter-kit/issues/137)
- [x] [Выпилить shared/helpers/react/withProps](https://github.com/fullstack-development/react-redux-starter-kit/issues/142)
- [x] [Выпилить shared/helpers/react/withComponent](https://github.com/fullstack-development/react-redux-starter-kit/issues/141)
- [x] [Выпилить shared/helpers[replaceObjectKeys, replaceObjectValues]](https://github.com/fullstack-development/react-redux-starter-kit/issues/139)
- [x] [Выпилить shared/helpers/react/areComponentsEqual](https://github.com/fullstack-development/react-redux-starter-kit/issues/140)

**Comment by kinda-neat** [comment]
выпить есть, а где мр?) или это уже в мастере? @prodderman @in19farkt

**Comment by Znack** [comment]
![image](https://user-images.githubusercontent.com/2928964/72133669-9a0e9c00-33b4-11ea-8771-7ca7414445ea.png)

Ты про это? @kinda-neat

**Comment by Znack** [comment]
@chmnkh в ПР написал, что после НГ займётся добиванием правок
